Repository projectsyn/component-fluentbit, pull requests merged in 2022-06, with the labels that each got.

#36 Add parameter to add generic helm values
  class/defaults.yml
  class/fluentbit.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#25 Update dependency docker.io/fluent/fluent-bit to v1.9.3
  class/defaults.yml
  tests/golden/defaults/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/defaults/fluentbit/fluentbit/10_custom_config.yaml
Labels: dependency

#38 Update `.sync.yml` for latest modulesync template
  .sync.yml
Labels: ignore

#41 Save Helm chart in tagged location
  class/fluentbit.yml
Labels: bug

#42 Switch to new Helm best practice format
  class/defaults.yml
  class/fluentbit.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: breaking

#43 Add support for configuring multiline parsers
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement
