Repository projectsyn/component-fluentbit, pull requests merged in 2024-08, with the labels that each got.

#70 Update Helm release fluent-bit to v0.47.5
  class/defaults.yml
  tests/golden/defaults/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/clusterrole.yaml
  tests/golden/defaults/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/clusterrolebinding.yaml
  tests/golden/defaults/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/defaults/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/service.yaml
  tests/golden/defaults/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/serviceaccount.yaml
  tests/golden/defaults/fluentbit/fluentbit/10_custom_config.yaml
Labels: dependency

#71 Support multiple instances
  class/defaults.yml
  class/fluentbit.yml
  component/app.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/fluentbit/apps/fluentbit.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/00_namespace.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/clusterrole.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/clusterrolebinding.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/service.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/serviceaccount.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/10_custom_config.yaml
Labels: enhancement

#72 Support custom secrets
  .cruft.json
  .github/workflows/test.yaml
  Makefile
  Makefile.vars.mk
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  renovate.json
  tests/config.yml
  tests/defaults.yml
  tests/golden/config/fluentbit/apps/fluentbit.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/00_namespace.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/clusterrole.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/clusterrolebinding.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/service.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/serviceaccount.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/10_custom_config.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/10_custom_secret.yaml
Labels: enhancement, bump:major

#73 Update docker.io/fluent/fluent-bit Docker tag to v3.1.5
  class/defaults.yml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/10_custom_config.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/10_custom_config.yaml
Labels: dependency, automerge, bump:patch

#75 Update docker.io/fluent/fluent-bit Docker tag to v3.1.6
  class/defaults.yml
  tests/golden/config/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/config/fluentbit/fluentbit/fluentbit/10_custom_config.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/01_fluentbit_helmchart/fluent-bit/templates/daemonset.yaml
  tests/golden/defaults/fluentbit/fluentbit/fluentbit/10_custom_config.yaml
Labels: dependency, automerge, bump:patch
